"""allow duplicate emails and add is_active to users

Revision ID: 88e3808ebb11
Revises: 8d4b1c0a3e9a
Create Date: 2025-12-03 15:41:12.799662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e3808ebb11'
down_revision = '8d4b1c0a3e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliverers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('deliverers_email_key'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')

    # Mettre is_active à TRUE pour les enregistrements existants
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('deliverers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('deliverers_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
